version: "3.9"
services:
  db:
    image: postgres:15.1-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url-shortener-db
      - PGDATA=/var/lib/postgresql/data/url-shortener-pgdata
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  api:
    depends_on:
      - db
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url-shortener-db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "5000:5000"

volumes:
  pgdata:
